"Create a basic neuron with 3 input"

In [9]:
inputs = [1.2, 5.3, 2.4]

In [10]:
inputs

[1.2, 5.3, 2.4]

In [11]:
weights = [3.1, 2.1, 8.7]

In [12]:
weights

[3.1, 2.1, 8.7]

In [13]:
bias = 3.0

In [14]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+ bias

In [15]:
output

38.730000000000004

In [16]:
'''create a simple layer of 3 neuron with 4 inputs'''

'create a simple layer of 3 neuron with 4 inputs'

In [17]:
inputs = [1.0, 2.0, 3.0, 2.5]

In [18]:
weight1 = [0.2, 0.8, -0.5, 1.0]
weight2 = [0.5, -0.91, 0.26, -0.5]
weight3 = [-0.26, -0.27, 0.17, 0.87]

In [19]:
bias1 = 2.1
bias2 = 3.1
bias3 = 0.6

In [20]:
output = [
    inputs[0]*weight1[0]+inputs[1]*weight1[1]+inputs[2]*weight1[2]+inputs[3]*weight1[3]+bias1,
    inputs[0]*weight2[0]+inputs[1]*weight2[1]+inputs[2]*weight2[2]+inputs[3]*weight2[3]+bias2,
    inputs[0]*weight3[0]+inputs[1]*weight3[1]+inputs[2]*weight3[2]+inputs[3]*weight3[3]+bias3,
]

In [21]:
print(output)

[4.9, 1.31, 2.485]


In [22]:
import numpy as np

In [23]:
inputs = [1.0, 2.0, 3.0, 2.5]

In [24]:
weightss =[[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]
         ]

In [25]:
weightss

[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

In [26]:
biases = [2.0, 3.0, 0.5]

In [27]:
output = np.dot(weightss, inputs) + biases

In [28]:
print(output)

[4.8   1.21  2.385]


In [29]:
'''create an layer of neurons using OOP'''

'create an layer of neurons using OOP'

In [30]:
np.random.seed(0)

In [31]:
X = [[1,2,3,2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [32]:
X

[[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

In [34]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.12 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    def forward_prop(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        


In [35]:
layer_1 = Layer_Dense(4, 5)
layer_1.forward_prop(X)
print(layer_1.output)

[[ 0.12909757  1.24780227  0.29354893  0.38185798  0.22621264]
 [-0.10019755  0.85015694  0.00352028  0.5364183   0.43632645]
 [-0.60915894  0.66826107  0.09585356 -0.41867488  0.05463651]]


In [37]:
layer_2 = Layer_Dense(5, 2)
layer_2.forward_prop(layer_1.output)

In [38]:
print(layer_2.output)

[[-0.09692747 -0.23834073]
 [-0.03366694 -0.14499031]
 [-0.15087154 -0.2470784 ]]
